"""esquema inicial

Revision ID: e3d5b79fdb28
Revises: 
Create Date: 2026-07-24 04:46:38.411229
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3d5b79fdb28'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash_descripcion', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('chars', sa.Integer(), nullable=False),
    sa.Column('creditos', sa.Integer(), nullable=False),
    sa.Column('ruta_mp3', sa.String(length=512), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'listo', 'error', name='estado_audio'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_asset_hash_descripcion'), 'audio_asset', ['hash_descripcion'], unique=True)
    op.create_table('bodega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_erp', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=True),
    sa.Column('es_operativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_erp'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('cedula', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('administrador', 'supervisor', 'supernumerario', name='rol_usuario'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_cedula'), 'usuario', ['cedula'], unique=True)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('nr_articulo', sa.BigInteger(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('descripcion_norm', sa.String(length=255), nullable=False),
    sa.Column('unidad', sa.Enum('unidad', 'kilogramo', 'litro', 'porcion', name='unidad_medida'), nullable=False),
    sa.Column('cantidad_erp', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('audio_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_asset_id'], ['audio_asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodega.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bodega_id', 'codigo_barras', name='uq_item_bodega_codigo'),
    sa.UniqueConstraint('bodega_id', 'descripcion_norm', name='uq_item_bodega_desc')
    )
    op.create_index('ix_item_bodega_desc', 'item', ['bodega_id', 'descripcion_norm'], unique=False)
    op.create_table('toma_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('abierta', 'cerrada', name='estado_toma'), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creada_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodega.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creada_por'], ['usuario.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario_bodega',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodega.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'bodega_id')
    )
    op.create_table('listado_conteo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toma_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('supernumerario_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'completado', 'cancelado', name='estado_listado'), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodega.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creado_por'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supernumerario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['toma_id'], ['toma_inventario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_listado_activo_toma_bodega', 'listado_conteo', ['toma_id', 'bodega_id'], unique=True, postgresql_where=sa.text("estado = 'activo'"))
    op.create_table('listado_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listado_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('contado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listado_id'], ['listado_conteo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listado_id', 'item_id', name='uq_listado_item')
    )
    op.create_table('conteo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listado_item_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_contada', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('contado_por', sa.Integer(), nullable=True),
    sa.Column('contado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metodo', sa.Enum('escaneo', 'busqueda', name='metodo_conteo'), nullable=False),
    sa.Column('entrada', sa.Enum('voz', 'manual', name='tipo_entrada'), nullable=False),
    sa.Column('intento_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contado_por'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listado_item_id'], ['listado_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conteo')
    op.drop_table('listado_item')
    op.drop_index('uq_listado_activo_toma_bodega', table_name='listado_conteo', postgresql_where=sa.text("estado = 'activo'"))
    op.drop_table('listado_conteo')
    op.drop_table('usuario_bodega')
    op.drop_table('toma_inventario')
    op.drop_index('ix_item_bodega_desc', table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_usuario_cedula'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('bodega')
    op.drop_index(op.f('ix_audio_asset_hash_descripcion'), table_name='audio_asset')
    op.drop_table('audio_asset')
    # ### end Alembic commands ###
